#!/usr/bin/env python

import subprocess

interface = input("Which interface will it be m'lord?"
new_mac = input("Which MAC do you want boss?"

print ("X Changing MAC address for " + interface + " to " + new_mac)

subprocess.call("ifconfig " + interface + " down", shell-True)
subprocess.call("ifconfig " + interface + " hw ether " + new_mac, shell-True)
subprocess.call("ifconfig " + interface + " up", shell-True)
